#!/bin/sh
ffmpeg -i "$1/video.mkv" -codec:v libx264 -profile:v high -preset slow -b:v 600k -bufsize 1200k -movflags +faststart "$1/video.mp4"

ffmpeg -y -i "$1/video.mkv" -codec:v libvpx -quality good -cpu-used 0 -b:v 500k -qmin 10 -qmax 42 -maxrate 500k -bufsize 1000k -threads 4 -an -pass 1 -f webm /dev/null
ffmpeg -i "$1/video.mkv" -codec:v libvpx -quality good -cpu-used 0 -b:v 500k -qmin 10 -qmax 42 -maxrate 500k -bufsize 1000k -threads 4 -pass 2 -f webm "$1/video.webm"
